version: '2'
services:

    composer-main:
        image: composer
        volumes:
            - "./:/app"
        command: 'install --ignore-platform-reqs --no-autoloader'

    composer-api:
        image: composer
        volumes:
            - "./vendor/andrejsstepanovs/moneyzaurus-api/web/app/:/app"
        command: 'install --ignore-platform-reqs'

    composer-web:
        image: composer
        volumes:
            - "./vendor/andrejsstepanovs/moneyzaurus-ci/:/app"
        command: 'install --ignore-platform-reqs'


    mysql:
        image: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - "db_data:/var/lib/mysql"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "8088:80"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql



    nginx-api:
        image: nginx:latest
        ports:
            - "81:80"
        restart: always
        volumes:
            - "./vendor/andrejsstepanovs/moneyzaurus-api/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./vendor/andrejsstepanovs/moneyzaurus-api/etc/ssl:/etc/ssl"
        depends_on:
            - php-fpm-api
            - mysql

    php-fpm-api:
        image: cytopia/php-fpm-7.1
        restart: always
        environment:
            - TIMEZONE=Europe/Berlin
            - PHP_XDEBUG_ENABLE=1
            - PHP_XDEBUG_REMOTE_HOST=localhost
            - PHP_XDEBUG_REMOTE_PORT=9000
        volumes:
            - "./vendor/andrejsstepanovs/moneyzaurus-api/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./vendor/andrejsstepanovs/moneyzaurus-api/web:/var/www/html"


    nginx-ci:
        image: nginx:latest
        ports:
            - "80:80"
        restart: always
        volumes:
            - "./vendor/andrejsstepanovs/moneyzaurus-ci/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./vendor/andrejsstepanovs/moneyzaurus-ci/etc/ssl:/etc/ssl"
            - "./vendor/andrejsstepanovs/moneyzaurus-ci:/var/www/html"

        depends_on:
            - php-fpm-ci
            - php-fpm-api
            - nginx-api

    php-fpm-ci:
        image: cytopia/php-fpm-7.1
        restart: always
        environment:
            - TIMEZONE=Europe/Berlin
            - PHP_XDEBUG_ENABLE=1
            - PHP_XDEBUG_REMOTE_HOST=localhost
            - PHP_XDEBUG_REMOTE_PORT=9000
        volumes:
            - "./vendor/andrejsstepanovs/moneyzaurus-ci/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./vendor/andrejsstepanovs/moneyzaurus-ci:/var/www/html"



volumes:
    db_data:
